name: VentureLibs
version: '1.0'
main: net.blockventuremc.VentureLibs
description: Plugin
api-version: '1.20'
has-open-classloader: true
loader: net.blockventuremc.VentureDependencyLoader

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: true